--- 
  components: 
    schemas: 
      RoadSegment: 
        $ref: "https://smart-data-models.github.io/dataModel.Transportation/RoadSegment/model.yaml#/RoadSegment"
  info: 
    description: >-
      This entity contains a harmonised geographic and contextual description of a
      road segment. A collection of road segments are used to describe a Road.
      Road segments can include several lanes. This data model allows to convey
      road segments made up of heterogeneous lanes (different in their usage,
      speed, height, etc.). Lanes are identified by using integer numbers between
      1 and n, being number 1 the lane to the right when going forwards. The
      forward direction is the direction denoted by the vector which goes from the
      segment"s start point to the segment"s end point. This is the same
      convention as the one used by OpenStreetMap. This entity is primarily
      associated with the Automotive and Smart City vertical segments and related
      IoT applications. This data model has been developed in cooperation with
      mobile operators and the GSMA.
    title: RoadSegment
    version: "1.0.0"
  openapi: "3.0.0"
  
  # These paths are merely representative.
  paths: 
    /ngsi-ld/v1/entities: 
      get: 
        description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
        parameters: 
          - 
            in: query
            name: type
            required: true
            schema: 
              enum: 
                - RoadSegment
              type: string
        responses: 
          ? "200"
          : 
            content: 
              application/ld+json: 
                examples: 
                  keyvalues: 
                    summary: "Key-Values Pairs"
                    value: 
                      - 
                        $ref: "https://smart-data-models.github.io/dataModel.Transportation/RoadSegment/examples/example-normalized.json"
                  normalized: 
                    summary: "Normalized NGSI-LD"
                    value: 
                      - 
                        $ref: "https://smart-data-models.github.io/dataModel.Transportation/RoadSegment/examples/example-normalized-ld.jsonld"
            description: OK
        tags: 
          - ngsi-ld
  tags: 
    - 
    
      description: "NGSI-LD Linked-data Format"
      name: ngsi-ld